services:
  - type: web
    name: ai-resume-analyzer
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python -m spacy download en_core_web_sm
    startCommand: streamlit run app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: STREAMLIT_SERVER_HEADLESS
        value: true
      - key: STREAMLIT_SERVER_PORT
        value: 10000 